import { Inter } from "next/font/google";
import "../globals.css";
import SidebarMenu from "../components/SidebarMenu";
import Header from "../components/Header"
import Wrapper from "../components/Wrapper";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard Create",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex">
          <div>
            <SidebarMenu />
          </div>
          <div className="pl-[250px] w-[calc(100% - 250px)] w-full">
            <Header />
            <Wrapper>
              {children}
            </Wrapper>
          </div>

        </main>

      </body>
    </html>
  );
}
